# Generated by Django 4.2.2 on 2023-08-09 03:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)])),
                ('about', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('mission', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('vision', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('verified', models.BooleanField(default=False)),
                ('location', models.CharField(choices=[('aguascalientes', 'AGUASCALIENTES'), ('baja california', 'BAJA CALIFORNIA'), ('baja california sur', 'BAJA CALIFORNIA SUR'), ('chihuahua', 'CHIHUAHUA'), ('chiapas', 'CHIAPAS'), ('campeche', 'CAMPECHE'), ('ciudad de mexico', 'CIUDAD DE MEXICO'), ('coahuila', 'COAHUILA'), ('colima', 'COLIMA'), ('durango', 'DURANGO'), ('guerrero', 'GUERRERO'), ('guanajuato', 'GUANAJUATO'), ('hidalgo', 'HIDALGO'), ('jalisco', 'JALISCO'), ('michoacan', 'MICHOACAN'), ('estado de mexico', 'ESTADO DE MEXICO'), ('morelos', 'MORELOS'), ('nayarit', 'NAYARIT'), ('nuevo leon', 'NUEVO LEON'), ('oaxaca', 'OAXACA'), ('puebla', 'PUEBLA'), ('quintana roo', 'QUINTANA ROO'), ('queretaro', 'QUERETARO'), ('sinaloa', 'SINALOA'), ('san luis potosi', 'SAN LUIS POTOSI'), ('sonora', 'SONORA'), ('tabasco', 'TABASCO'), ('tlaxcala', 'TLAXCALA'), ('tamaulipas', 'TAMAULIPAS'), ('veracruz', 'VERACRUZ'), ('yucatan', 'YUCATAN'), ('zacatecas', 'ZACATECAS')], max_length=50)),
                ('image', models.ImageField(null=True, upload_to='images/company')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)])),
                ('lastname', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(50)])),
                ('expected_salary', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('modality', models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], max_length=10)),
                ('location', models.CharField(choices=[('aguascalientes', 'AGUASCALIENTES'), ('baja california', 'BAJA CALIFORNIA'), ('baja california sur', 'BAJA CALIFORNIA SUR'), ('chihuahua', 'CHIHUAHUA'), ('chiapas', 'CHIAPAS'), ('campeche', 'CAMPECHE'), ('ciudad de mexico', 'CIUDAD DE MEXICO'), ('coahuila', 'COAHUILA'), ('colima', 'COLIMA'), ('durango', 'DURANGO'), ('guerrero', 'GUERRERO'), ('guanajuato', 'GUANAJUATO'), ('hidalgo', 'HIDALGO'), ('jalisco', 'JALISCO'), ('michoacan', 'MICHOACAN'), ('estado de mexico', 'ESTADO DE MEXICO'), ('morelos', 'MORELOS'), ('nayarit', 'NAYARIT'), ('nuevo leon', 'NUEVO LEON'), ('oaxaca', 'OAXACA'), ('puebla', 'PUEBLA'), ('quintana roo', 'QUINTANA ROO'), ('queretaro', 'QUERETARO'), ('sinaloa', 'SINALOA'), ('san luis potosi', 'SAN LUIS POTOSI'), ('sonora', 'SONORA'), ('tabasco', 'TABASCO'), ('tlaxcala', 'TLAXCALA'), ('tamaulipas', 'TAMAULIPAS'), ('veracruz', 'VERACRUZ'), ('yucatan', 'YUCATAN'), ('zacatecas', 'ZACATECAS')], max_length=50)),
                ('about', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('image', models.ImageField(null=True, upload_to='images/user')),
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
