# Generated by Django 4.2.2 on 2023-06-23 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='user',
            new_name='base_user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='base_user',
        ),
    ]
