# Generated by Django 4.2.2 on 2023-08-27 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sectors', '0001_initial'),
        ('authentication', '0003_alter_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sectors.sector'),
        ),
    ]
