# Generated by Django 4.2.2 on 2023-10-15 06:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_company_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images/company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images/user'),
        ),
    ]
