# Generated by Django 4.2.2 on 2023-11-05 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyroles',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
