# Generated by Django 4.2.2 on 2023-11-06 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_companyroles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyroles',
            name='name',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
