# Generated by Django 4.2.2 on 2023-10-29 17:53

import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 10, 29))])),
                ('end_date', models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date(2023, 10, 29))])),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(20)])),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
