MODALITY_CHOICES = [
    ('presencial', 'Presencial'),
    ('remoto', 'Remoto'),
    ('hibrido', 'Híbrido'),
]

POSITION_CHOICES = [
    ('administrador', 'Administrador'),
    ('analista de datos', 'Analista de datos'),
    ('arquitecto', 'Arquitecto'),
    ('auxiliar', 'Auxiliar'),
    ('becario', 'Becario'),
    ('cocinero', 'Cocinero'),
    ('contador', 'Contador'),
    ('desarrollador', 'Desarrollador'),
    ('devops', 'DevOps'),
    ('diseñador', 'Diseñador'),
    ('electricista', 'Electricista'),
    ('enfermero', 'Enfermero'),
    ('fisico', 'Físico'),
    ('ingeniero', 'Ingeniero'),
    ('matematico', 'Matemático'),
    ('medico', 'Médico'),
    ('mesero', 'Mesero'),
    ('musico', 'Músico'),
    ('profesor', 'Profesor'),
    ('tester', 'Tester'),
    ('vendedor', 'Vendedor'),
    ('otro', 'Otro')
]


LOCATION_CHOICES = [
    ('aguascalientes', 'AGUASCALIENTES'),
    ('baja california', 'BAJA CALIFORNIA'),
    ('baja california sur', 'BAJA CALIFORNIA SUR'),
    ('chihuahua', 'CHIHUAHUA'),
    ('chiapas', 'CHIAPAS'),
    ('campeche', 'CAMPECHE'),
    ('ciudad de mexico', 'CIUDAD DE MEXICO'),
    ('coahuila', 'COAHUILA'),
    ('colima', 'COLIMA'),
    ('durango', 'DURANGO'),
    ('guerrero', 'GUERRERO'),
    ('guanajuato', 'GUANAJUATO'),
    ('hidalgo', 'HIDALGO'),
    ('jalisco', 'JALISCO'),
    ('michoacan', 'MICHOACAN'),
    ('estado de mexico', 'ESTADO DE MEXICO'),
    ('morelos', 'MORELOS'),
    ('nayarit', 'NAYARIT'),
    ('nuevo leon', 'NUEVO LEON'),
    ('oaxaca', 'OAXACA'),
    ('puebla', 'PUEBLA'),
    ('quintana roo', 'QUINTANA ROO'),
    ('queretaro', 'QUERETARO'),
    ('sinaloa', 'SINALOA'),
    ('san luis potosi', 'SAN LUIS POTOSI'),
    ('sonora', 'SONORA'),
    ('tabasco', 'TABASCO'),
    ('tlaxcala', 'TLAXCALA'),
    ('tamaulipas', 'TAMAULIPAS'),
    ('veracruz', 'VERACRUZ'),
    ('yucatan', 'YUCATAN'),
    ('zacatecas', 'ZACATECAS')
]


SECTOR_CHOICES = [
    ('educacion', 'Educacion'),
    ('salud', 'Salud'),
    ('alimentos', 'Alimentos'),
    ('financiero', 'Finanzas'),
    ('software', 'Software'),
    ('tecnologias de la informacion', 'Tecnologías de la información (TI)'),
    ('transporte', 'Transporte'),
    ('turismo', 'Turismo'),
    ('ventas', 'Ventas'),
    ('telecomunicaciones', 'Telecomunicaciones'),
    ('otro', 'Otro'),
]
